import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        padding: 40,
        backgroundColor: '#000000',
        color: '#FFFFFF',
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 30,
        borderBottomWidth: 1,
        borderBottomColor: '#333333',
        paddingBottom: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
        letterSpacing: 1,
    },
    subtitle: {
        fontSize: 10,
        color: '#666666',
        marginTop: 5,
        textTransform: 'uppercase',
        letterSpacing: 2,
    },
    logo: {
        fontSize: 10,
        color: '#10b981', // Emerald 500
        textTransform: 'uppercase',
        letterSpacing: 2,
        fontWeight: 'bold',
    },
    section: {
        marginBottom: 20,
        padding: 20,
        backgroundColor: '#111111',
        borderRadius: 8,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    label: {
        fontSize: 10,
        color: '#888888',
    },
    value: {
        fontSize: 12,
        fontWeight: 'bold',
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#333333',
    },
    totalValue: {
        fontSize: 16,
        color: '#10b981',
        fontWeight: 'bold',
    },
    disclaimer: {
        position: 'absolute',
        bottom: 40,
        left: 40,
        right: 40,
        fontSize: 8,
        color: '#444444',
        textAlign: 'center',
    },
});

interface BudgetPDFProps {
    tripName: string;
    totalBudget: number;
    totalSpent: number;
    currency: string;
    categories: { label: string; value: number }[];
    burnRate: number;
}

export const BudgetPDF = ({ tripName, totalBudget, totalSpent, currency, categories, burnRate }: BudgetPDFProps) => (
    <Document>
        <Page size="A4" style={styles.page}>

            {/* Header */}
            <View style={styles.header}>
                <View>
                    <Text style={styles.title}>Financial Brief</Text>
                    <Text style={styles.subtitle}>{tripName}</Text>
                </View>
                <Text style={styles.logo}>SAFAR.AI INTELLIGENCE</Text>
            </View>

            {/* Summary Section */}
            <View style={styles.section}>
                <View style={styles.row}>
                    <Text style={styles.label}>TOTAL BUDGET</Text>
                    <Text style={styles.value}>{currency} {totalBudget.toLocaleString()}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>TOTAL ALLOCATED</Text>
                    <Text style={styles.value}>{currency} {totalSpent.toLocaleString()}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>REMAINING</Text>
                    <Text style={{ ...styles.value, color: totalBudget - totalSpent < 0 ? '#ef4444' : '#10b981' }}>
                        {currency} {(totalBudget - totalSpent).toLocaleString()}
                    </Text>
                </View>
            </View>

            {/* Burn Rate */}
            <View style={styles.section}>
                <Text style={{ ...styles.subtitle, marginBottom: 15, color: '#10b981' }}>VELOCITY METRICS</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>DAILY BURN RATE</Text>
                    <Text style={styles.value}>{currency} {Math.round(burnRate).toLocaleString()} / day</Text>
                </View>
            </View>

            {/* Breakdown */}
            <View style={styles.section}>
                <Text style={{ ...styles.subtitle, marginBottom: 15 }}>ALLOCATION BREAKDOWN</Text>
                {categories.map((cat, i) => (
                    <View key={i} style={styles.row}>
                        <Text style={styles.label}>{cat.label.toUpperCase()}</Text>
                        <Text style={styles.value}>{currency} {cat.value.toLocaleString()}</Text>
                    </View>
                ))}
            </View>

            {/* Disclaimer */}
            <Text style={styles.disclaimer}>
                Generated by SafarAI Financial Intelligence. Market rates are estimates.
            </Text>
        </Page>
    </Document>
);
